export const basicStrategy = {
  hard: {
    8: {
      2: "Hit",
      3: "Hit",
      4: "Hit",
      5: "Double",
      6: "Double",
      7: "Hit",
      8: "Hit",
      9: "Hit",
      10: "Hit",
      11: "Hit",
    },
    9: {
      2: "Hit",
      3: "Double",
      4: "Double",
      5: "Double",
      6: "Double",
      7: "Hit",
      8: "Hit",
      9: "Hit",
      10: "Hit",
      11: "Hit",
    },
    10: {
      2: "Double",
      3: "Double",
      4: "Double",
      5: "Double",
      6: "Double",
      7: "Double",
      8: "Double",
      9: "Double",
      10: "Hit",
      11: "Hit",
    },
    12: {
      2: "Hit",
      3: "Hit",
      4: "Stand",
      5: "Stand",
      6: "Stand",
      7: "Hit",
      8: "Hit",
      9: "Hit",
      10: "Hit",
      11: "Hit",
    },
    16: {
      2: "Stand",
      3: "Stand",
      4: "Stand",
      5: "Stand",
      6: "Stand",
      7: "Hit",
      8: "Hit",
      9: "Hit",
      10: "Hit",
      11: "Surrender",
    },
  },
  soft: {
    13: {
      2: "Hit",
      3: "Hit",
      4: "Double",
      5: "Double",
      6: "Double",
      7: "Hit",
      8: "Hit",
      9: "Hit",
      10: "Hit",
      11: "Hit",
    },
    18: {
      2: "Stand",
      3: "Double",
      4: "Double",
      5: "Double",
      6: "Double",
      7: "Stand",
      8: "Stand",
      9: "Hit",
      10: "Hit",
      11: "Hit",
    },
  },
  pair: {
    2: {
      2: "Split",
      3: "Split",
      4: "Split",
      5: "Split",
      6: "Split",
      7: "Split",
      8: "Hit",
      9: "Hit",
      10: "Hit",
      11: "Hit",
    },
    8: {
      2: "Split",
      3: "Split",
      4: "Split",
      5: "Split",
      6: "Split",
      7: "Split",
      8: "Split",
      9: "Split",
      10: "Hit",
      11: "Hit",
    },
    11: {
      2: "Split",
      3: "Split",
      4: "Split",
      5: "Split",
      6: "Split",
      7: "Split",
      8: "Split",
      9: "Split",
      10: "Split",
      11: "Split",
    },
  },
};
